### ISSUE TITLE
Integration with transifex & the nextcloud-bot

### ISSUE THREAD

**Issue by AndyScherzinger** [linfaservice/cloudgallery#1]
Hi everybody,

the idea mentioned in the Nextcloud forum would be to integrate this project into the Nextcloud transifex project to get this app translated to many more languages. See https://help.nextcloud.com/t/cloud-gallery-nextcloud-photos-on-android/20872/5
So pinging @MorrisJobke for evaluation 😃

**Comment by MorrisJobke** [comment]
Just give the @nextcloud-bot push access to the master branch of this repo and tell me where the l10n files are located and I will take care of the integration.

**Comment by damikael** [comment]
Thanks @MorrisJobke . nextcloud-bot added, the translations files are in /app/i18n/
Let me know if you need other.

**Comment by MorrisJobke** [comment]
Added via https://github.com/linfaservice/cloudgallery/commit/feb35d06e1d4fd14b9740a130cba8591c74f23a7 and the bot is also running. Now we need to wait for translators on transifex. You could also jump in there: https://www.transifex.com/nextcloud/nextcloud/dashboard/

Keep in mind, that transifex is the source of the translations and changes to all other files than en.json will be overwritten. So if you need to do an update in the italian version: go to transifex, do it there and wait for the sync bot to push it to your repo (every night at ~3 am Europe/Berlin this will happen).

Happy translating! 🚀 

https://www.transifex.com/nextcloud/nextcloud/linfaservice-cloudgallery/

(I initially pushed your italian translation once to transifex as well.)

**Comment by AndyScherzinger** [comment]
Awesome! Thanks for your support @MorrisJobke ❤️

**Comment by damikael** [comment]
Wonderful! :) thanks
