### ISSUE TITLE
Notify and give choice to accept invalid cert on https

### ISSUE THREAD

**Issue by tim-web** [linfaservice/cloudgallery#14]
During login, if the https certificate is invalid, Cloud Gallery Android app fails login simply stating to "check parameters".
The user should be notified of the the invalid cert and given a choice to proceed (accept invalid cert), not proceed, or fail back to http if available.
Tim

**Comment by 3PO** [comment]
Same problem here, i cannot login to nextcloud. :(

**Comment by damikael** [comment]
Http connection is now allowed (android version 1.0)
