### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by Spartachetto** [linfaservice/cloudgallery#16]
Do you plan to release the app on F-Droid too?

That would be great!

**Comment by damikael** [comment]
Yes, we will submit the request for packaging on F-Droid with the first public version on the next days :-)

**Comment by damikael** [comment]
Sorry, unfortunately the app can not be released to F-Droid due to F-Droid inclusion policy (https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy). Cloud Gallery infact use Firebase and Crashlitycs.
