### ISSUE TITLE
Provide app on F-Droid

### ISSUE THREAD

**Issue by stefan-niedermann** [linfaservice/cloudgallery#20]

**Comment by damikael** [comment]
Sorry, unfortunately the app can not be released to F-Droid due to F-Droid inclusion policy (https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy). Cloud Gallery infact use Firebase and Crashlitycs.

**Comment by stefan-niedermann** [comment]
Maybe providing an own F-Droid repository might be a solution? I have read at f-droid.org that it is as easy as pushing static files to a git repository :-)

https://f-droid.org/en/repomaker/

**Comment by damikael** [comment]
It's not scheduled for now but thanks for advice, we'll can consider this for future.
