### ISSUE TITLE
Removing translation resource from Transifex

### ISSUE THREAD

**Issue by rakekniven** [linfaservice/cloudgallery#23]
Hello,

the app looks deprecated. Am I wrong?

If so I would like to remove the resource from Transifex.

If you ask why? See https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312

Existing translations are not lost. They will remain in this repository.

Please provide feedback.

Thank you

**Comment by rakekniven** [comment]
@damikael What is your view about this repository?

**Comment by damikael** [comment]
Hell @rakekniven , I hope to have time to work on a new version of app. 
I'll feedback you when the new version will be online if we will can connect it to transifex again.
Thanks

**Comment by rakekniven** [comment]
Connection to Transifex has not been cancelled right now.
Is it ok for you to stop sync?

**Comment by damikael** [comment]
Yes, for now sync can be stopped.
