### ISSUE TITLE
Empty gallery window

### ISSUE THREAD

**Issue by devz3r0** [linfaservice/cloudgallery#3]
I am using the standard gallery app with NC12.0.2 installed that app, 
set ip up with mx ssl-url user and dedicated app password, without any specific folder, but the result is this:

![grafik](https://user-images.githubusercontent.com/13016719/30545303-7fb3d998-9c89-11e7-984a-9faf6dff3a98.png)

**Comment by damikael** [comment]
Please wait for next version of the app in which we 'll insert external logging capability. So we'll can investigate better. Thanks

**Comment by tacruc** [comment]
Same issue here on Samsung Galaxy S5 neu Android 6.0.1

**Comment by damikael** [comment]
First of check your logs, can you confirm me that the nextcloud address configured is set to **https://** and not simply http://

**Comment by tacruc** [comment]
Sorry stupid question. Where can I find the log?

**Comment by devz3r0** [comment]
the address in the app is set to https, my instance is reachable by both yet, because of some legacy instances which get removed soon.

Additional to that, I have the same issue on a one plus 2 lineage os 14, Android 7.1.2

**Comment by damikael** [comment]
If you want, join the alpha test team at the follow link:
https://play.google.com/apps/testing/it.linfaservice.cloudgallery

installing this alpha version you can touch the version number on bottom right on the main screen to send me an email with application log.
Thanks

**Comment by devz3r0** [comment]
i opted in yesterday but still don't get any updates.

**Comment by damikael** [comment]
It's now available as new public beta version (0.8)
you can touch the version number on bottom right on the main screen to send me an email with application log.
Waiting for your test :)

**Comment by devz3r0** [comment]
@damikael There must be another bugfix too, because I just updated it, and it started to work, without changing anything in the settings

**Comment by damikael** [comment]
yes @devz3r0, I've worked on some fix on version 0.8 but I wasn't sure if it could work on other devices. I'm glad to know that it works now :) 
Let me know if you like Cloud Gallery and if you have any advices. We plan to realease the first production version soon.
Thanks

**Comment by damikael** [comment]
@tacruc can you confirm it works for you too?

**Comment by devz3r0** [comment]
@damikael It works on my oneplus2 and pixel C, so it must be something with my server configuration.
About an advice, please implement some local caching with probably a manual update function from the current location and recursive, because if you have mounted some webdav devices it loads ages every time when you open the app.

Additional an ability to change the settings f.e. the root-images folder would be great too.

**Comment by tacruc** [comment]
Hey with the new Version the app works sending an email works as well. Haven't had time to do intensive checks.
Thanks

**Comment by damikael** [comment]
Good, then I can close this issue. For any other problem or advice you can always open another issue.
Thank you for testing and for your advices.
We'll release first production version soon, and this is also thanks to your help :)

**Comment by Juvenciodas** [comment]
Hi damikael the app is unable to connect to my nextcloud server.
I keep getting (Error connection. please check parameters.)

I have setup https and also have sync apps connected thru https. Not sure if I am missing something.
