### ISSUE TITLE
unclear translation string

### ISSUE THREAD

**Issue by AndyScherzinger** [linfaservice/cloudgallery#4]
@damikael one string that imho needs fixing:

> Do you need a Nextcloud account? Click here for illimitate space for Cloud Gallery

"illimitate"  --> Did you mean "unlimited"? 😃

**Comment by damikael** [comment]
Oops :) yes, it's unlimited

**Comment by AndyScherzinger** [comment]
PR is #5 :)

**Comment by damikael** [comment]
Merged. Thanks @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Always a pleasure @damikael :)
