### ISSUE TITLE
String unused

### ISSUE THREAD

**Issue by MorrisJobke** [linfaservice/cloudgallery#6]
Hi, there is this string:

```
Do you need a Nextcloud account? Click here for unlimited space for Cloud Gallery
```

Why is it there, because if people have their own instance, there is no easy way to upgrade their storage. Beside that I also could not find it anywhere in the source code.

----

Just found it: It still holds the old name: https://github.com/linfaservice/cloudgallery/blob/8716adda322b8fc97e91edf36c704b92adb82541/app/pages/settings/settings.html#L14 and seem to link to https://www.operweb.com/nextcloud-gallery/ (which is italian only):

https://github.com/linfaservice/cloudgallery/blob/8716adda322b8fc97e91edf36c704b92adb82541/app/pages/settings/settings.component.ts#L77-L79

Spotted by @nickvergessen

**Comment by damikael** [comment]
Hi @MorrisJobke,
I've fixed the string, thanks.
I've already reported to webmaster of operweb.com to translate the page in english.

**Comment by MorrisJobke** [comment]
> I've already reported to webmaster of operweb.com to translate the page in english.

Is there any reason why this provider is mentioned specifically? We also provide a list of providers on our page for example: https://nextcloud.com/providers/

**Comment by damikael** [comment]
Operweb is partner of the Cloud Gallery project
